force-app/main/default/objects/News__b/News__b.object-meta.xml
<CustomObject>
    <label>News</label>
    <pluralLabel>News</pluralLabel>
</CustomObject>

force-app/main/default/objects/News__b/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/News__b/fields/Created__c.field-meta.xml
<CustomField>
    <fullName>Created__c</fullName>
    <label>Created</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/News__b/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/News__b/fields/ImageLink__c.field-meta.xml
<CustomField>
    <fullName>ImageLink__c</fullName>
    <label>ImageLink</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/News__b/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/News__b/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/newsHelper.cls
public with sharing class newsHelper {
    private static final Integer MAX_LIMIT = 2000;

    @AuraEnabled(Cacheable=true)
    public static List<News__b> getNews(Integer lim) {
        List<News__b> news = new List<News__b>();

        if (lim > MAX_LIMIT) {
            lim = MAX_LIMIT;
        }

        for (News__b n : [
                SELECT Title__c, Description__c, Author__c, Link__c, ImageLink__c, Created__c
                FROM News__b
                LIMIT :lim
        ]) {
            news.add(n);
        }

        return news;
    }
}