force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <label>Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Close__c.field-meta.xml
<CustomField>
    <fullName>Close__c</fullName>
    <label>Close</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Close_Previous__c.field-meta.xml
<CustomField>
    <fullName>Close_Previous__c</fullName>
    <label>Close Previous</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Day_Range__c.field-meta.xml
<CustomField>
    <fullName>Day_Range__c</fullName>
    <label>Day Range</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Exchange__c.field-meta.xml
<CustomField>
    <fullName>Exchange__c</fullName>
    <label>Exchange</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <label>Open</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Volume_Average__c.field-meta.xml
<CustomField>
    <fullName>Volume_Average__c</fullName>
    <label>Volume Average</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Weeks_Range__c.field-meta.xml
<CustomField>
    <fullName>Weeks_Range__c</fullName>
    <label>Weeks Range</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/Timeseries__b.object-meta.xml
<CustomObject>
    <label>Timeseries</label>
    <pluralLabel>Timeseries</pluralLabel>
</CustomObject>

force-app/main/default/objects/Timeseries__b/fields/Close__c.field-meta.xml
<CustomField>
    <fullName>Close__c</fullName>
    <label>Close</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/High__c.field-meta.xml
<CustomField>
    <fullName>High__c</fullName>
    <label>High</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Low__c.field-meta.xml
<CustomField>
    <fullName>Low__c</fullName>
    <label>Low</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Moment__c.field-meta.xml
<CustomField>
    <fullName>Moment__c</fullName>
    <label>Moment</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <label>Open</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Timeseries</relationshipLabel>
    <relationshipName>Timeseries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/stockHelper.cls
public with sharing class stockHelper {
    private static final String RANGE_SEPARATOR = ' - ';

    @AuraEnabled(cacheable=true)
    public static List<Stock__c> getStocks() {
        List<Stock__c> stocks = new List<Stock__c>();

        for (Stock__c s : [
                SELECT Id, Logo__c, Company_Name__c, Name, Exchange__c, Close__c, Currency_Code__c, Change__c, Change_Percent__c, Open__c, Volume__c, Day_Range__c, Close_Previous__c, Volume_Average__c, Weeks_Range__c
                FROM Stock__c
                LIMIT 20
        ]) {
            stocks.add(s);
        }

        return scaleStocks(stocks);
    }

    @AuraEnabled(cacheable=true)
    public static Stock__c getStock(String stockId) {
        if (stockId == null) {
            return [SELECT Id, Logo__c, Name, Company_Name__c, Exchange__c, Close__c, Change__c, Change_Percent__c, Currency_Code__c FROM Stock__c LIMIT 1];
        }
        return [SELECT Id, Logo__c, Name, Company_Name__c, Exchange__c, Close__c, Change__c, Change_Percent__c, Currency_Code__c FROM Stock__c WHERE Id = :stockId LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static List<Timeseries__b> getTimeseries(String stockId, String interval) {
        List<Timeseries__b> timeseries = new List<Timeseries__b>();

        for (Timeseries__b t : [
                SELECT Moment__c, High__c, Close__c, Open__c, Low__c, Volume__c
                FROM Timeseries__b
                WHERE Stock__c = :stockId AND Interval__c = :interval
                LIMIT 100
        ]) {
            timeseries.add(t);
        }

        return timeseries;
    }

    private static List<Stock__c> scaleStocks(List<Stock__c> stocks) {
        for(Stock__c s : stocks) {
            s.Close__c = scaleDecimal(s.Close__c);
            s.Change__c = scaleDecimal(s.Change__c);
            s.Change_Percent__c = scaleDecimal(s.Change_Percent__c);
            s.Open__c = scaleDecimal(s.Open__c);
            s.Close_Previous__c = scaleDecimal(s.Close_Previous__c);
            s.Volume__c = scaleDecimal(s.Volume__c);
            s.Volume_Average__c = scaleDecimal(s.Volume_Average__c);
            s.Day_Range__c = scaleRange(s.Day_Range__c);
            s.Weeks_Range__c = scaleRange(s.Weeks_Range__c);
        }

        return stocks;
    }

    private static Decimal scaleDecimal(Decimal value) {
        return value != null ? value.setScale(2) : value;
    }

    private static String scaleRange(String range) {
        List<String> values = range.split(RANGE_SEPARATOR);
        String left = String.valueOf(scaleDecimal(Decimal.valueOf(values[0])));
        String right = String.valueOf(scaleDecimal(Decimal.valueOf(values[1])));

        return left + RANGE_SEPARATOR + right;
    }
}