force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Close__c.field-meta.xml
<CustomField>
    <fullName>Close__c</fullName>
    <label>Close</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <label>Open</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/Timeseries__b.object-meta.xml
<CustomObject>
    <label>Timeseries</label>
    <pluralLabel>Timeseries</pluralLabel>
</CustomObject>

force-app/main/default/objects/Timeseries__b/fields/Close__c.field-meta.xml
<CustomField>
    <fullName>Close__c</fullName>
    <label>Close</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/High__c.field-meta.xml
<CustomField>
    <fullName>High__c</fullName>
    <label>High</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Low__c.field-meta.xml
<CustomField>
    <fullName>Low__c</fullName>
    <label>Low</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Moment__c.field-meta.xml
<CustomField>
    <fullName>Moment__c</fullName>
    <label>Moment</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <label>Open</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Timeseries</relationshipLabel>
    <relationshipName>Timeseries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timeseries__b/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/timeseriesHelper.cls
public without sharing class timeseriesHelper {
    @AuraEnabled(cacheable=true)
    public static List<Timeseries__b> getPortfolioTimeseries(String stockId, String interval) {
        List<Timeseries__b> timeseries = new List<Timeseries__b>();

        for (Timeseries__b t : [
                SELECT Moment__c, High__c, Close__c, Open__c, Low__c, Volume__c
                FROM Timeseries__b
                WHERE Stock__c = :stockId AND Interval__c = :interval
                LIMIT 100
        ]) {
            timeseries.add(t);
        }

        return timeseries;
    }
}