force-app/main/default/objects/Forex__c/Forex__c.object-meta.xml
<CustomObject>
    <label>Forex</label>
    <nameField>
        <label>Forex Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forex</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forex__c/fields/Change_Percent__c.field-meta.xml
<CustomField>
    <fullName>Change_Percent__c</fullName>
    <label>Change Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/forexHelper.cls
public with sharing class forexHelper {
    @AuraEnabled(Cacheable=true)
    public static List<Forex__c> getForex() {
        List<Forex__c> forexList = new List<Forex__c>();

        for (Forex__c f : [
                SELECT Name, Close__c, Change_Percent__c
                FROM Forex__c
                LIMIT 5
        ]) {
            f.Close__c = f.Close__c.setScale(2);
            f.Change_Percent__c = f.Change_Percent__c.setScale(2);

            forexList.add(f);
        }

        return forexList;
    }
}